package com.briup.apps.poll.dao;

import com.briup.apps.poll.bean.Ansers;
import com.briup.apps.poll.bean.AnsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    long countByExample(AnsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    int deleteByExample(AnsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    int insert(Ansers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    int insertSelective(Ansers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    List<Ansers> selectByExampleWithBLOBs(AnsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    List<Ansers> selectByExample(AnsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    Ansers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") Ansers record, @Param("example") AnsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Ansers record, @Param("example") AnsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    int updateByExample(@Param("record") Ansers record, @Param("example") AnsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    int updateByPrimaryKeySelective(Ansers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Ansers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_answers
     *
     * @mbg.generated Mon Jun 25 17:33:20 CST 2018
     */
    int updateByPrimaryKey(Ansers record);
}